### ISSUE TITLE
AtttributeError: 'Nonetype' object has no attribute 'replace'

### ISSUE THREAD

**Issue by jaystary** [geoalchemy/geoalchemy2#469]
Hi,

i think in the latest release there is a docstring missing for the inner function leading to an attribute error:
https://github.com/geoalchemy/geoalchemy2/blob/80e738d09c6929305376f245bbd38fe7ff22b3f8/geoalchemy2/utils.py#L11

Do you want me to make a PR for it?

**Comment by adrien-berchet** [comment]
Hi @jaystary ,
Thanks for your report!
Could you just tell me in which context you need a docstring for this inner function?
Anyway, any PR is always welcome :⁠-⁠)

**Comment by adrien-berchet** [comment]
Hi @jaystary 
Could you give more details on this issue please? Especially in which context you get this AttributeError.

**Comment by marcm-ml** [comment]
starting python with the `-OO` option will remove docstrings from executed python code which in turn will throw this error message. I think it would make sense to catch this error in the decorator function and thus prevent this. As this function is cosmetic nature, it does not hurt to not have the templated variables in the docstrings for production-like settings where this option is typically used.

Reproducible script:
```bash
python -OO -c "import geolachemy2"
```

**Comment by adrien-berchet** [comment]
Ooooh ok, interesting! Thanks for these details!
I guess you are the only one to run `geoalchemy2` in optimized mode :smile: 
I understand now, and indeed it should be fixed, I will try to do this soon.

**Comment by adrien-berchet** [comment]
@marcm-ml could you check that #484 fixes your issue properly plz?

**Comment by adrien-berchet** [comment]
@jaystary and @marcm-ml I pushed the `0.14.3` release which should solve this issue. Feel free to reopen if you still experience this issue.

**Comment by marcm-ml** [comment]
Thanks. Will check out the release and comment here if error still persists (it's fixed when testing with "python -OO -c 'import geolachemy'")
